# Generated by Django 5.0.7 on 2025-07-19 12:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True, verbose_name='Chave de Sessão'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem do Produto'),
        ),
    ]
