# render.yaml
# Este arquivo define a configuração para implantar o projeto Jeci Store no Render.com.

services:
  - type: web # Define este serviço como um aplicativo web
    name: jecistore # Nome do seu serviço web no Render
    env: python # O ambiente de tempo de execução é Python
    # Comando de construção: instala dependências, coleta arquivos estáticos e executa migrações
    buildCommand: |
      pip install -r requirements.txt # Instala as dependências listadas em requirements.txt
      python manage.py collectstatic --noinput # Coleta todos os arquivos estáticos
      python manage.py migrate # Aplica as migrações do banco de dados
    # Comando de inicialização: usa Gunicorn para servir a aplicação Django
    startCommand: gunicorn jecistore_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars: # Variáveis de ambiente para o seu aplicativo Django
      - key: PYTHON_VERSION # Define a versão do Python
        value: 3.13.4 # <--- ALINHE ESTE VALOR com a versão do Python que você está usando localmente
      - key: DJANGO_SECRET_KEY # Chave secreta do Django
        generateValue: true # O Render pode gerar um valor seguro para você
      - key: DJANGO_DEBUG # Modo de depuração do Django
        value: "False" # <--- SEMPRE defina como "False" em produção
      - key: WEB_CONCURRENCY # Número de workers Gunicorn (ajuste com base nos núcleos da CPU do seu servidor)
        value: 4 # Um bom ponto de partida, ajuste conforme necessário
      - key: DATABASE_URL # Variável de ambiente para a URL completa do banco de dados
        fromDatabase:
          name: jecistore-database # Nome do banco de dados PostgreSQL
          property: connectionString # Obtém a string de conexão completa
      - key: STORE_WHATSAPP_NUMBER # Número do WhatsApp da loja
        value: "5561998504516" # Seu número de WhatsApp (com código do país e DDD)
      - key: DJANGO_ALLOWED_HOSTS # Para ALLOWED_HOSTS em produção
        value: jecy.onrender.com # Use vírgula para múltiplos hosts: "jecy.onrender.com,meudominio.com"

databases: # Configuração do banco de dados
  - name: jecistore-database # Nome do seu banco de dados no Render
    type: postgres # Tipo de banco de dados: PostgreSQL
    plan: free # Plano do banco de dados (pode ser 'standard' para mais recursos em produção)
